/* 
 * Klootzakken API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Klootzakken.Api.Model
{
    /// <summary>
    /// GameView
    /// </summary>
    [DataContract]
    public partial class GameView :  IEquatable<GameView>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GameView" /> class.
        /// </summary>
        /// <param name="You">You.</param>
        /// <param name="Others">Others.</param>
        public GameView(You You = default(You), List<OtherPlayer> Others = default(List<OtherPlayer>))
        {
            this.You = You;
            this.Others = Others;
        }
        
        /// <summary>
        /// Gets or Sets You
        /// </summary>
        [DataMember(Name="you", EmitDefaultValue=false)]
        public You You { get; set; }
        /// <summary>
        /// Gets or Sets Others
        /// </summary>
        [DataMember(Name="others", EmitDefaultValue=false)]
        public List<OtherPlayer> Others { get; set; }
        /// <summary>
        /// Gets or Sets CenterCard
        /// </summary>
        [DataMember(Name="centerCard", EmitDefaultValue=false)]
        public string CenterCard { get; private set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GameView {\n");
            sb.Append("  You: ").Append(You).Append("\n");
            sb.Append("  Others: ").Append(Others).Append("\n");
            sb.Append("  CenterCard: ").Append(CenterCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as GameView);
        }

        /// <summary>
        /// Returns true if GameView instances are equal
        /// </summary>
        /// <param name="other">Instance of GameView to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GameView other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.You == other.You ||
                    this.You != null &&
                    this.You.Equals(other.You)
                ) && 
                (
                    this.Others == other.Others ||
                    this.Others != null &&
                    this.Others.SequenceEqual(other.Others)
                ) && 
                (
                    this.CenterCard == other.CenterCard ||
                    this.CenterCard != null &&
                    this.CenterCard.Equals(other.CenterCard)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.You != null)
                    hash = hash * 59 + this.You.GetHashCode();
                if (this.Others != null)
                    hash = hash * 59 + this.Others.GetHashCode();
                if (this.CenterCard != null)
                    hash = hash * 59 + this.CenterCard.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
